### ISSUE TITLE
Saving mirror files and Hybrid

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#146] opened 2016-11-27 21:09 UTC
Dear Luca
I attach a zip file with an Oasys file and the needed files to run it.
I requested to write all the mirror files. It seems that it is overwriting the previous since 4 and 5 are not saved. It also writes other files that should not. 
All mirror are written without the Hybrid after the slit.

[Issues with saving mirror files.zip](https://github.com/lucarebuffi/ShadowOui/files/615034/Issues.with.saving.mirror.files.zip)

I had another issue that may be we spoke about it. Mirror 2 was getting limits from another one despite the fact that did not have limits. With the figure error file the problem was solved

Best regards,

Ruben

**Comment by lucarebuffi** [comment] 2016-11-28 13:42
First part of the issue is solved, the calculated hybrid beam was not propagating the OE number as well, and the numeration was restarting with a wrong number, and that was easy to fix.

Regarding:

_"Mirror 2 was getting limits from another one despite the fact that did not have limits. With the figure error file the problem was solved"_

I apologise, but I am not able to understand what you mean. In the example you gave me, mirrors has a finite dimension, but possibly I am not catching the point.

**Comment by lucarebuffi** [comment] 2016-11-28 13:46
The first issue has been fixed in ShadowOui version 1.3.74

**Comment by lucarebuffi** [comment] 2016-11-30 14:25
Ruben, could you please try to explain better:

_"Mirror 2 was getting limits from another one despite the fact that did not have limits. With the figure error file the problem was solved"_?

I still not understand what you mean. Could you please send me a workspace with the issue as you usually do? I want to fix stupid bugs before joining you in APS. thanks

**Comment by RubenReininger** [comment] 2016-11-30 15:38
I tried but did not succeed. I think it was the way I created the workspace. I will let you know if I see it again (or others…)

Best regards,

Ruben
On Nov 30, 2016, at 8:25 AM, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:


Ruben, could you please try to explain better:

"Mirror 2 was getting limits from another one despite the fact that did not have limits. With the figure error file the problem was solved"?

I still not understand what you mean. Could you please send me a workspace with the issue as you usually do? I want to fix stupid bugs before joining you in APS. thanks

**Closed** 2016-12-01 15:39 UTC
Labels: bug
